Preferences: add custom icon setting
Aryan20/Logomenu pull request #61
Opened 2023-11-18 18:46 UTC by halfmexican

Closes #16 

![image](https://github.com/Aryan20/Logomenu/assets/103920890/3bd3248b-bfbf-4ee6-8614-483219e67fee)

I not entirely sure if I'm happy with the current UI, but this implementation works. I'd appreciate any suggestions and feedback.

2023-11-18 18:57 UTC, Aryan20 commented
Thanks! I will check the implementation and will think of something in terms of UI soon.

2023-11-23 00:50 UTC, halfmexican commented
![image](https://github.com/Aryan20/Logomenu/assets/103920890/19248755-00a3-4563-83aa-3190c7a32d8e)

2023-11-23 00:50 UTC, halfmexican commented
I think I want to add a icon preview next to the button

2023-12-20 23:37 UTC, Aryan20 commented
Hey! Any updates?

2023-12-20 23:38 UTC, Aryan20 requested changes

2023-12-20 23:38 UTC, Aryan20 commented
Finally got GitHub to make the comments public lol

2023-12-28 04:20 UTC, halfmexican commented
life has gotten in the way.

2023-12-30 16:53 UTC, Aryan20 commented
> life has gotten in the way.

Ah okay, no issues, take your time and happy holidays :)

2024-01-11 17:37 UTC, halfmexican commented on PrefsLib/adw.js
> +        iconSettingsGroup.add(customIconRow);
This sounds completely reasonable, will implement

2024-01-14 09:29 UTC, Aryan20 approved these changes
LGTM!

2024-01-14 09:30 UTC, merged

2024-01-14 09:30 UTC, Aryan20 commented
Thanks for working on this :D